name: Deploy to Production

on:
  push:
    branches:
      - main
      - terraform-conf
      - develop
  pull_request:
    branches:
      - main
      - terraform-conf
      - develop


jobs:
  build:
    name: Deploy Application
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        shell: bash


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create
        run: touch /opt/test18.txt
