name: Deploy to Production

on:
  push:
    branches:
      - main
      - terraform-conf
      - develop

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to Production
        run: /opt/touch test18.txt
