name: Deploy to Production

on:
  push:
    branches:
      - main
      - terraform-conf
      - develop
  pull_request:
    branches:
      - main
      - terraform-conf
      - develop

jobs:
  build:
    name: Deploy Application
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2        
      - name: Deploy to Production
        run: touch /opt/test18.txt
