name: Deploy to Production

on:
  push:
    branches:
      - main
      - terraform-conf
      - develop
  pull_request:
    branches:
      - main
      - terraform-conf
      - develop


jobs:
  build:
    name: Deploy Application
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3       
      - name: Deploy to Production
        run: touch /opt/test18.txt
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
